export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const SET_MOVIES = "SET_MOVIES";
export const SHOW_GLOBAL_SPINNER = "SHOW_GLOBAL_SPINNER";
export const HIDE_GLOBAL_SPINNER = "HIDE_GLOBAL_SPINNER";
